### ISSUE TITLE
Hi guys, I have a question or two, so miners must use the specific firmware or they wont be able to mine on the pool, is that correct? Thanks Cminor

### ISSUE THREAD

**Issue by Cminor-pools** [decred/dcrpool#339]

**Comment by jholdstock** [comment]
The listed firmware versions are ones which are confirmed to work against the current dcrpool code.

There is a chance newer firmware versions will work, but they have not been tested and could require further dev work.

I'm going to close this issue because it doesn't describe a defect or work to be completed. To ask other questions, please visit us on https://chat.decred.org
